/**
 * Documentation generation.
 *
 * The normative artefacts are machine-readable, which means the prose that indexes
 * them is derivable. Generating that index rather than hand-maintaining it removes a
 * whole class of drift: a schema can be added and cannot be forgotten, because the
 * index is regenerated from the schemas themselves.
 *
 * Two modes:
 *   npm run docs:generate   writes docs/generated/
 *   npm run docs:check      regenerates in memory and fails if anything differs
 *
 * Only docs/generated/ is generated. docs/*.md is hand-written normative prose and is
 * never touched by this script.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  API_VERSION,
  Reporter,
  asRecordArray,
  asString,
  asStringArray,
  isRecord,
  listFiles,
  loadSchemaRegistry,
  readYamlFile,
  repoPath,
  REPO_ROOT,
  SPEC_VERSION,
} from './validate-schema.js';

const OUTPUT_DIR = join(REPO_ROOT, 'docs', 'generated');

interface GeneratedFile {
  readonly path: string;
  readonly contents: string;
}

function table(headers: readonly string[], rows: readonly (readonly string[])[]): string {
  const escape = (cell: string): string => cell.replace(/\|/g, '\\|').replace(/\n/g, ' ');
  const lines = [
    `| ${headers.join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.map(escape).join(' | ')} |`),
  ];
  return `${lines.join('\n')}\n`;
}

function readYamlRecords(directory: string): { path: string; document: Record<string, unknown> }[] {
  return listFiles(join(REPO_ROOT, directory), ['.yaml']).flatMap((file) => {
    const parsed = readYamlFile(file);
    return isRecord(parsed) ? [{ path: repoPath(file), document: parsed }] : [];
  });
}

function buildSchemas(): GeneratedFile {
  const entries = loadSchemaRegistry();
  const rows = entries.map((entry) => [
    entry.id.replace('https://amasario.dev/spec/v1/schema/', ''),
    typeof entry.document.title === 'string' ? entry.document.title : '',
    asStringArray(entry.document.required).join(', ') || '(none)',
  ]);
  const contents = `# Generated schema index

Generated by \`npm run docs:generate\` from \`schema/\`. Do not edit by hand.

Specification version: \`${SPEC_VERSION}\`, apiVersion: \`${API_VERSION}\`.

${entries.length} schemas. The root of every document is closed (\`additionalProperties: false\`),
so an unrecognised field is rejected rather than ignored.

${table(['Schema', 'Title', 'Required at root'], rows)}
Each schema's \`$id\` is the identifier used by every \`$ref\` in the repository, so a schema
can only be referenced by an identifier that resolves.
`;
  return { path: join(OUTPUT_DIR, 'schemas.md'), contents };
}

function buildTaxonomies(): GeneratedFile {
  const records = readYamlRecords('taxonomies');
  const sections = records.map(({ path, document }) => {
    const terms = asRecordArray(document.terms);
    const rows = terms.map((term) => [
      asString(term.id) ?? '',
      asString(term.label) ?? '',
      asString(term.description)?.replace(/\s+/g, ' ').trim() ?? '',
    ]);
    const openness = asString(document.openness);
    const usedBy = asRecordArray(document.usedBy)
      .map((entry) => `\`${asString(entry.file) ?? ''}${asString(entry.pointer) ?? ''}\``)
      .join(', ');
    return `## ${asString(document.name) ?? path}

Source: \`${path}\` — openness: **${openness}** — consumers must handle unknown terms: \`${String(
      document.consumersMustHandleUnknown,
    )}\`

${(asString(document.description) ?? '').replace(/\s+/g, ' ').trim()}

${table(['Term', 'Label', 'Description'], rows)}
Enforced at: ${usedBy || '_none declared_'}
`;
  });
  return {
    path: join(OUTPUT_DIR, 'taxonomies.md'),
    contents: `# Generated taxonomy index

Generated by \`npm run docs:generate\` from \`taxonomies/\`. Do not edit by hand.

\`scripts/validate-taxonomies.ts\` checks that every declared location holds exactly the
full term set. A term set that is restated anywhere else fails validation, because a
restated enumeration is one waiting to drift.

${sections.join('\n')}`,
  };
}

function buildModels(): GeneratedFile {
  const records = readYamlRecords('models');
  const sections = records.map(({ path, document }) => {
    const fields = asRecordArray(document.fields);
    const rows = fields.map((field) => [
      asString(field.name) ?? '',
      asString(field.type) ?? '',
      asString(field.requirement) ?? '',
      asString(field.description)?.replace(/\s+/g, ' ').trim() ?? '',
    ]);
    const schemaRef = isRecord(document.schema) ? document.schema : {};
    const invariants = asStringArray(document.invariants)
      .map((line) => `- ${line}`)
      .join('\n');
    const nonGoals = asStringArray(document.nonGoals)
      .map((line) => `- ${line}`)
      .join('\n');
    return `## ${asString(document.name) ?? path}

Source: \`${path}\` — concept: \`${asString(document.concept) ?? ''}\` — schema: \`${
      asString(schemaRef.id) ?? ''
    }\`

${(asString(document.description) ?? '').replace(/\s+/g, ' ').trim()}

${table(['Field', 'Type', 'Requirement', 'Description'], rows)}
**Invariants**

${invariants}

**Non-goals**

${nonGoals}
`;
  });
  return {
    path: join(OUTPUT_DIR, 'models.md'),
    contents: `# Generated model index

Generated by \`npm run docs:generate\` from \`models/\`. Do not edit by hand.

The requirement column is checked against the schema: \`always\` must be a schema-required
field, \`conditional\` must be required by a conditional branch, and \`rule\` and \`optional\`
must not be schema-required. A model cannot describe a guarantee the schema does not make.

${sections.join('\n')}`,
  };
}

function buildRules(): GeneratedFile {
  const records = readYamlRecords('rules');
  const all: {
    id: string;
    severity: string;
    file: string;
    statement: string;
    fixtures: string[];
  }[] = [];
  for (const { path, document } of records) {
    for (const rule of asRecordArray(document.rules)) {
      all.push({
        id: asString(rule.id) ?? '',
        severity: asString(rule.severity) ?? '',
        file: path,
        statement: (asString(rule.statement) ?? '').replace(/\s+/g, ' ').trim(),
        fixtures: asStringArray(rule.fixtures),
      });
    }
  }
  all.sort((a, b) => a.id.localeCompare(b.id));
  const rows = all.map((rule) => [
    rule.id,
    rule.severity,
    rule.statement,
    rule.fixtures.join(', '),
  ]);
  return {
    path: join(OUTPUT_DIR, 'rules.md'),
    contents: `# Generated rule index

Generated by \`npm run docs:generate\` from \`rules/\`. Do not edit by hand.

${all.length} rules across ${records.length} files. Every rule names at least one fixture that
demonstrates it, which \`scripts/validate-rules.ts\` enforces: a rule nothing demonstrates is
an assertion nothing checks.

${table(['Rule', 'Severity', 'Statement', 'Fixtures'], rows)}`,
  };
}

function buildInventory(): GeneratedFile {
  const inventory = {
    apiVersion: API_VERSION,
    specVersion: SPEC_VERSION,
    schemas: loadSchemaRegistry()
      .map((entry) => entry.id)
      .sort(),
    taxonomies: readYamlRecords('taxonomies')
      .map(({ document }) => ({
        id: asString(document.id) ?? '',
        openness: asString(document.openness) ?? '',
        terms: asRecordArray(document.terms).map((term) => asString(term.id) ?? ''),
      }))
      .sort((a, b) => a.id.localeCompare(b.id)),
    models: readYamlRecords('models')
      .map(({ path, document }) => ({
        id: asString(document.id) ?? path,
        concept: asString(document.concept) ?? '',
      }))
      .sort((a, b) => a.id.localeCompare(b.id)),
    rules: readYamlRecords('rules')
      .flatMap(({ document }) =>
        asRecordArray(document.rules).map((rule) => ({
          id: asString(rule.id) ?? '',
          severity: asString(rule.severity) ?? '',
        })),
      )
      .sort((a, b) => a.id.localeCompare(b.id)),
    fixtures: readYamlRecords('fixtures')
      .map(({ path, document }) => ({
        id: asString(document.id) ?? path,
        kind: asString(document.kind) ?? '',
      }))
      .sort((a, b) => a.id.localeCompare(b.id)),
    examples: readYamlRecords('examples')
      .map(({ path, document }) => ({
        id: asString(document.id) ?? path,
        target: asString(document.target) ?? '',
      }))
      .sort((a, b) => a.id.localeCompare(b.id)),
    vectors: readYamlRecords('vectors')
      .map(({ path, document }) => ({
        id: asString(document.id) ?? path,
        operation: asString(document.operation) ?? '',
      }))
      .sort((a, b) => a.id.localeCompare(b.id)),
  };
  return {
    path: join(OUTPUT_DIR, 'inventory.json'),
    contents: `${JSON.stringify(inventory, null, 2)}\n`,
  };
}

function buildIndex(files: readonly GeneratedFile[]): GeneratedFile {
  const list = files
    .map((file) => `- \`${repoPath(file.path)}\``)
    .sort()
    .join('\n');
  return {
    path: join(OUTPUT_DIR, 'README.md'),
    contents: `# Generated documentation

Generated by \`npm run docs:generate\`. Do not edit anything in this directory by hand:
\`npm run docs:check\` regenerates it and fails when the committed copy differs.

Generated files:

${list}

The hand-written normative prose lives in \`docs/\` and is not generated. Where prose and a
machine-readable artefact disagree, the artefact is correct and the prose is a bug, as
described in \`CONTRIBUTING.md\`.
`,
  };
}

function generate(): GeneratedFile[] {
  const files = [buildSchemas(), buildTaxonomies(), buildModels(), buildRules(), buildInventory()];
  files.push(buildIndex(files));
  return files;
}

function main(): number {
  const check = process.argv.includes('--check');
  const reporter = new Reporter(check ? 'generate-docs --check' : 'generate-docs');
  const files = generate();

  if (check) {
    for (const file of files) {
      const where = repoPath(file.path);
      let existing: string | undefined;
      try {
        existing = readFileSync(file.path, 'utf8');
      } catch {
        existing = undefined;
      }
      if (existing === undefined) {
        reporter.fail(where, 'generated file is missing; run npm run docs:generate');
      } else if (existing !== file.contents) {
        reporter.fail(where, 'generated file is out of date; run npm run docs:generate');
      }
    }
    // A file removed from the generator would otherwise linger in the committed output.
    const expected = new Set(files.map((file) => repoPath(file.path)));
    let present: string[];
    try {
      present = readdirSync(OUTPUT_DIR).map((entry) => `docs/generated/${entry}`);
    } catch {
      present = [];
    }
    for (const entry of present) {
      if (!expected.has(entry)) reporter.fail(entry, 'generated file has no producer; remove it');
    }
    return reporter.finish(`${files.length} generated files`);
  }

  for (const file of files) {
    mkdirSync(dirname(file.path), { recursive: true });
    writeFileSync(file.path, file.contents, 'utf8');
  }
  reporter.note(`wrote ${files.length} files to docs/generated/`);
  return reporter.finish(`${files.length} generated files`);
}

if (fileURLToPath(import.meta.url) === resolve(process.argv[1] ?? '')) {
  process.exitCode = main();
}
